resource "local_file" "github_ci_configuration" {
  filename = "${path.root}/../../.github/generated.env"

  content = <<EOF
# DO NOT EDIT
# This file is generated by /tests/terraform/generate.tf

echo AWS_REGION="${data.aws_region.current.name}" >> $GITHUB_ENV
echo AWS_ROLE_TO_ASSUME="${aws_iam_role.github_ci.arn}" >> $GITHUB_ENV
EOF
}