name: pr-acceptance-tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '*.md'

permissions:
  id-token: write  # required for aws-actions/configure-aws-credentials@v1

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Configure
        run: |
          ./.github/generated.env
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - run: cd tests && make tests